language: node_js

# Use container-based infrastructure
sudo: false

node_js:
  - "8"

before_install: cd osa-7

install:
  - yarn

script:
  - yarn run ci

after_script:
  - cd ..
  - ./deploytoheroku osa-7
